name: CI - DevOps Status Frontend

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - staging
    paths:
      - 'devops-status-fe/**'
      - '.github/workflows/devops-status-fe-docker-build-push.yaml'

permissions:
  contents: read

jobs:
  build-push:
    env:
      IMAGE: devops-status-frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Import Secrets
        id: import-secrets
        uses: hashicorp/vault-action@v3
        with:
          url: ${{ secrets.VAULT_ADDRESS }}
          token: ${{ secrets.VAULT_TOKEN }}
          tlsSkipVerify: true
          secrets: |
            DevOps-k8s/data/artifactory url | DOCKER_REGISTRY_URL ;
            DevOps-k8s/data/artifactory username | DOCKER_REGISTRY_USER ;
            DevOps-k8s/data/artifactory token | DOCKER_REGISTRY_TOKEN ;

      - name: Generate build ID
        id: prep
        run: |
          branch=${GITHUB_REF##*/}
          sha=${GITHUB_SHA::8}
          ts=$(date +%s)
          build_id="${branch}-${sha}-${ts}"
          if [[ "$branch" == "staging" ]]; then
            semver_tag="rc"
            build_id="${build_id}-${semver_tag}"
          fi
          echo "BUILD_ID=${build_id}" >> "$GITHUB_ENV"
          echo "BUILD_ID=${build_id}" >> "$GITHUB_OUTPUT"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        run: |
          REGISTRY="${{ steps.import-secrets.outputs.DOCKER_REGISTRY_URL }}"
          docker build -f devops-status-fe/Dockerfile -t "${REGISTRY}/${{ env.IMAGE }}:${{ env.BUILD_ID }}" .

      - name: Login to Artifactory Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ steps.import-secrets.outputs.DOCKER_REGISTRY_URL }}
          username: ${{ steps.import-secrets.outputs.DOCKER_REGISTRY_USER }}
          password: ${{ steps.import-secrets.outputs.DOCKER_REGISTRY_TOKEN }}

      - name: Docker push
        run: |
          REGISTRY="${{ steps.import-secrets.outputs.DOCKER_REGISTRY_URL }}"
          docker push "${REGISTRY}/${{ env.IMAGE }}:${{ env.BUILD_ID }}"
